### ISSUE TITLE
Image alignment of homepage tiles

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy-hub#1142]
I love the new `Galaxy for` tiles.  The 'Tool Developers' line throws off the midline alignment of all the images, though, since it's two lines.  It'd be nice to align the text by either getting that to one line, or adding structure to the icon part to keep them docked to the bottom of the tile.

![image](https://user-images.githubusercontent.com/155398/150141871-6992f057-65cd-468a-b9ea-d2cbd214f0ab.png)

**Comment by beatrizserrano** [comment]
I tried to do align the text to the top, but didn't know how to align the image to the bottom :( Any ideas on how to change the component to do that?

**Comment by bwlang** [comment]
Maybe an easy path… for Tool builders could be one line?



On Jan 19, 2022, at 9:47 AM, Beatriz Serrano-Solano ***@***.******@***.***>> wrote:

EXTERNAL SENDER



I tried to do align the text to the top, but didn't know how to align the image to the bottom :( Any ideas on how to change the component to do that?

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgalaxyproject%2Fgalaxy-hub%2Fissues%2F1142%23issuecomment-1016537802&data=04%7C01%7Clanghorst%40neb.com%7C4fc8994bbb0f46c7aef008d9db5aaaa6%7C77cefbc6b3d64d6a9f740664881c384b%7C0%7C0%7C637782004763685968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E1sMHte5D3fqCcKv77zv2H%2B5cdFnz1j8nr2yHcP9V%2FE%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAPBRHX6544TEUV4GAZNLDUW3FJNANCNFSM5MJ65K4A&data=04%7C01%7Clanghorst%40neb.com%7C4fc8994bbb0f46c7aef008d9db5aaaa6%7C77cefbc6b3d64d6a9f740664881c384b%7C0%7C0%7C637782004763685968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=g2e21n5SAc8Kmj6s27XYaXxu0RGqJuUWWiNaxcmOfp8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clanghorst%40neb.com%7C4fc8994bbb0f46c7aef008d9db5aaaa6%7C77cefbc6b3d64d6a9f740664881c384b%7C0%7C0%7C637782004763685968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7%2FZSeFoTU6SsZQzS2E7JIzFRH3%2FR5BFmKgxOiAu3UaQ%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Clanghorst%40neb.com%7C4fc8994bbb0f46c7aef008d9db5aaaa6%7C77cefbc6b3d64d6a9f740664881c384b%7C0%7C0%7C637782004763685968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kw2ACYrN4a0XUTtxNj4%2B7p%2BTgIKy9bpEcqkse9kDsDM%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Brad Langhorst, Ph.D.
Applications and Product Development Group Leader
New England Biolabs
***@***.******@***.***>
