### ISSUE TITLE
improve UX of linking within hub

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy-hub#132]
instead of `/src/whatever/index.md` we should be able to just link to `whatever`

**Comment by dannon** [comment]
There was a really long thread somewhere where we discussed this, but I can't find it right now :(

Basically, the absolute paths were a compromise we came to because of how rendering of markdown within github and the github web edit/preview interface works, to more easily support web editing.

We actually *did* have /src/ and /index.md dropped, at one point.

**Comment by dannon** [comment]
@martenson Now that I think about it, you probably *can* just use links like ```/whatever```, we just don't encourage it since it will not render in github correctly.  Were you finding otherwise?

**Comment by dannon** [comment]
(closing this since I think I addressed the question above)
