### ISSUE TITLE
Gitter Sidecar dead / delaying page loading

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy-hub#2360]
Looks like Gitter sidecar is dead, https://sidecar.gitter.im/dist/sidecar.v1.js is no longer responding

Should it be removed?

On my firefox the hub pages stay for a veeeery long time in a loading state, waiting for [sidecar.gitter.im](https://sidecar.gitter.im/dist/sidecar.v1.js). And on usegalaxy.fr, for some reason the embedded home page stays blank until firefox gives up trying to load it.

**Comment by dannon** [comment]
@abretaud Thanks for noticing this.  I'm surprised it's blocking and causing a delay since it should only be fired *after* the page loads, but I guess that doesn't matter because it's definitely dead now that Gitter is fully integrated into Matrix.  I'm removing the integration for now, and we can look for (or not) a new matrix-friendly option.

**Comment by dannon** [comment]
There were actually three pages including sidecar directly as a part of the contents instead of injecting it as most of them did, which explains the blocking you saw.

**Comment by abretaud** [comment]
Ok thanks!
