### ISSUE TITLE
News metadata, pages and summaries

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy-hub#37]
News and Events need to be tagged with two fields in the yaml frontmatter, like:

 -date: '2016-12-01'
 -tease: "Here's a small teaser line with more info"

With these defined, contents will automatically show up in feeds like on the homepage, under News, Events, etc.

**Comment by dannon** [comment]
Examples:
6598a58fad06c113692790023e4631c64f157b09
39426ae1e157540cf4cafecbc0536fe9565cea7c

**Comment by tnabtaf** [comment]
Events have their own issue #137.  Renaming this issue to be about News.

**Comment by tnabtaf** [comment]
Here's a proposed spec for News page tags:

## `title`

- Required
- Meaning
  - Short title for news item
- Use
  - Becomes the news item page title
  - Shown in the new list as the name of the news item. 
- Format:
  - free text all on one line.  Should be wrapped in quotes.

## `tease`

- Optional
- Meaning
  - Short bit of additional text about the news item
  - Meant to complement, rather than replace `title` (?) 
- Use
  - display with the event title, when space allows.
- Format:
  - free text all on one line. Should be wrapped in quotes

## `date`

- Required
- Meaning
  - Date the news item was posted, or last modified
- Use
  - Determines where in the news list the item shows up.
- Format:
  - `'YYYY-MM-DD'` - including single quotes

I'll dive in and see if these make sense.

**Comment by dannon** [comment]
This was handled in #164
