### ISSUE TITLE
brilliantly handle redirects from wiki to hub

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy-hub#40]
I believe we have to set up a remarkably well working redirects because the old wiki urls are linked throughout the internets and you know...urls are forever.

Given that there will be efforts to move things around the hub (for better, like here: https://github.com/galaxyproject/galaxy-site/issues/36) it is even more important to redirect smart.

Sadly, we will have to maintain, at least for major wiki pages, the redirects together with the new content. Let's create a way to do that.

**Comment by dannon** [comment]
Yep, we definitely want to handle redirects well.   @tnabtaf and I talked about this a bit last week and I think and think most of them should be straightforward (and this could be tested with a script, of course), and Dave was saying he could manually work up a list of the others, as a requirement to swapping from new.galaxyproject.org to the primary domain.

**Comment by martenson** [comment]
Small part of this issue is how to handle images that have been embedded in other pages but sourced from old wiki. This mostly applies to logos but also some other graphics.

**Comment by tnabtaf** [comment]
Not sure if this is how we want to do this, but Moin supports automatic redirecting to another page.  We haven't enabled it in the past because of security issues.  However, without general public edit access, that's not a problem.

This would also allow us to access wiki pages and history for a while afterward.

Eventually we would just want to replace that with web server redirects.

- https://moinmo.in/HelpOnProcessingInstructions#A.23refresh
- https://moinmo.in/HelpOnConfiguration#various

**Comment by martenson** [comment]
An issue with letting MoinMoin live (and do such things for us) is that it might be a security problem given its lack of development activity (and also a hurdle to maintain mostly due to the same reasons).

**Comment by dannon** [comment]
I provided a mapping of all the known (to me) moved pages to @tnabtaf who hand-curated it a bit and passed it along to @natefoo.  We should be covered, leaving this issue open until it's live though.

**Comment by martenson** [comment]
I believe the redirects file should be transparent (in this repo?) and easily editable. So we can drop stuff and reorganize easily.

**Comment by martenson** [comment]
Are we also going to redirect `new.***` to `***`?

**Comment by dannon** [comment]
Yep, we should do that.

**Comment by tnabtaf** [comment]
@martenson sent redirect mapping to @natefoo last week.  @natefoo any estimate on when that will go live?  And if we post the mapping somewhere, can we periodically update it?

@martenson, @dannon The mapping is a TSV file.  Should I put that in Git, and if so where?

**Comment by martenson** [comment]
@tnabtaf that is for @natefoo to decide imo; it should be somewhere easily modifiable where playbook will keep it synced with webserver

**Comment by martenson** [comment]
https://galaxyproject.org//admin/tools/tool-config-syntax/ > should go to https://docs.galaxyproject.org/en/latest/dev/schema.html

**Comment by dannon** [comment]
I overhauled some of the redirects and it's all functional now, including error pages.  I disagree about that particular page being a redirect.  I think with the plan to transclude this content we'd be best off keeping the page (obviously with a link to the current docs, as it is now), without redirecting, for now.   Anyway, we can continue to work on that, but I'm closing this parent issue because wiki->hub redirecting is complete.

**Comment by martenson** [comment]
@dannon I am missing information on how to add/modify redirects. Did it end up in a playbook somewhere?
