### ISSUE TITLE
loaded data gets deleted

### ISSUE THREAD

**Issue by Shaimaa177** [galaxyproject/galaxy-hub#726]
I have a problem whenever i load a set of data from UCSC main table browser, the previously loaded data disappears

**Comment by jennaj** [comment]
Hi @Shaimaa177 There was a prior issue that logged you out of Galaxy when downloading data from the UCSC Table Browser. It wasn't a consistent fail and we believe it was related to query-quotas at UCSC. Logging into Galaxy will add the newly downloaded data into a new history in your account, and you will need to consolidate datasets between histories. Copies of datasets in your own account do not consume extra quota space, but you can still purge the histories you don't need once you have a copy of the data in the history you want to work in. 

Inconvenient, but we don't have another solution right now. This is the open ticket: https://github.com/galaxyproject/galaxy/issues/11374

Try again or consolidate your data into the working history, as repeating the query tends to also work. Next time, please post your question to the Galaxy Help forum https://help.galaxyproject.org/. 

Please include details in questions: where you are working (URL), what is going wrong, screenshots. The more details you provide, the more the community can help. Most questions should go to that forum, not created as an issue here. If a problem requires an issue ticket, we'll help get it triaged to the correct repo associated with this project. 

There was actually an open ticket at GHelp already about this -- and are probably others (in the context of other analysis, so bit hard to find). I added the workaround/issue ticket posted here to that particular post since it was well described and should be easier to find now: https://help.galaxyproject.org/t/output-of-ucse-table-browser-get-data-creates-a-new-history-and-logs-the-user-out/3300

Thanks!
